branches: ['main']
plugins:
  - "@semantic-release-cargo/semantic-release-cargo"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - 
    - "@semantic-release/github"
    - assets:
      - path: "dist/x86_64-unknown-linux-musl/contemplate-x86_64-unknown-linux-musl"
        label: "x86_64-unknown-linux-musl"
      - path: "dist/x86_64-unknown-linux-gnu/contemplate-x86_64-unknown-linux-gnu"
        label: "x86_64-unknown-linux-gnu"
      - path: "dist/i686-unknown-linux-musl/contemplate-i686-unknown-linux-musl"
        label: "i686-unknown-linux-musl"
      - path: "dist/i686-unknown-linux-gnu/contemplate-i686-unknown-linux-gnu"
        label: "i686-unknown-linux-gnu"
      - path: "dist/x86_64-apple-darwin/contemplate-x86_64-apple-darwin"
        label: "x86_64-apple-darwin"
      - path: "dist/aarch64-unknown-linux-musl/contemplate-aarch64-unknown-linux-musl"
        label: "aarch64-unknown-linux-musl"
      - path: "dist/aarch64-unknown-linux-gnu/contemplate-aarch64-unknown-linux-gnu"
        label: "aarch64-unknown-linux-gnu"
      - path: "dist/aarch64-apple-darwin/contemplate-aarch64-apple-darwin"
        label: "aarch64-apple-darwin"
      - path: "dist/SHA256SUMS.txt"
        label: "SHA256SUMS.txt"
  -
    - "@semantic-release/git"
    - assets:
      - "Cargo.toml"
      - "Cargo.lock"
      - "CHANGELOG.md"
  -
    - "@semantic-release-plus/docker"
    - name: infrarun/contemplate
      registry: ghcr.io
      skipLogin: true
