site_name: Contemplate Documentation
theme:
  name: material
  features:
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.top
    - navigation.sections
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/infrarun/contemplate
plugins:
- search
markdown_extensions:
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
nav:
- Home: index.md
- Getting started:
  - getting_started/overview.md
- Data Sources:
  - Overview: data_sources/overview.md
  - Environment: data_sources/environment.md
  - File: data_sources/file.md
  - Kubernetes: data_sources/kubernetes.md
- Templates:
  - Overview: templates/overview.md
  - Filters: templates/filters.md
- Advanced Usage:
  - Debugging: advanced/debugging.md
  - Integrating other Software: advanced/integration.md
exclude_docs: |
  !/templates/
